drivers/mtk/video: Fix type specifier missing
 disp_recovery.h:23:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 extern ddp_dsi_config(enum DISP_MODULE_ENUM module,
 ~~~~~~ ^
 int
 1 error generated.

Signed-off-by: zainarbani <zaintsyariev@gmail.com>